name: Main CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit

  system-ops:
    needs: docker-build
    uses: ./.github/workflows/system-ops.yml
    secrets: inherit

  system-ops:
    needs: docker-build
    uses: ./.github/workflows/system-ops.yml
    secrets: inherit